/**
 * @file keys.h
 * @author Gregory Mitchell (me@gmitch215.xyz)
 * @brief Key macro definitions for CmdFX for usage in key-related events
 * @version 0.2.0
 * @date 2025-04-24
 * 
 * @copyright Copyright (c) 2025
 * 
 */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#if defined(_WINDOWS) || defined(_WIN32) || defined(__CYGWIN__) || defined(__MINGW32__)
#include <winuser.h>

#define KEY_A 0x41
#define KEY_B 0x42
#define KEY_C 0x43
#define KEY_D 0x44
#define KEY_E 0x45
#define KEY_F 0x46
#define KEY_G 0x47
#define KEY_H 0x48
#define KEY_I 0x49
#define KEY_J 0x4A
#define KEY_K 0x4B
#define KEY_L 0x4C
#define KEY_M 0x4D
#define KEY_N 0x4E
#define KEY_O 0x4F
#define KEY_P 0x50
#define KEY_Q 0x51
#define KEY_R 0x52
#define KEY_S 0x53
#define KEY_T 0x54
#define KEY_U 0x55
#define KEY_V 0x56
#define KEY_W 0x57
#define KEY_X 0x58
#define KEY_Y 0x59
#define KEY_Z 0x5A
#define KEY_0 0x30
#define KEY_1 0x31
#define KEY_2 0x32
#define KEY_3 0x33
#define KEY_4 0x34
#define KEY_5 0x35
#define KEY_6 0x36
#define KEY_7 0x37
#define KEY_8 0x38
#define KEY_9 0x39
#define KEY_ENTER VK_RETURN
#define KEY_ESCAPE VK_ESCAPE
#define KEY_BACKSPACE VK_BACK
#define KEY_TAB VK_TAB
#define KEY_SPACE VK_SPACE
#define KEY_MINUS VK_SUBTRACT
#define KEY_EQUAL VK_ADD
#define KEY_LEFT_BRACKET VK_LBRACKET
#define KEY_RIGHT_BRACKET VK_RBRACKET
#define KEY_BACKSLASH VK_OEM_5
#define KEY_SEMICOLON VK_OEM_1
#define KEY_APOSTROPHE VK_OEM_7
#define KEY_COMMA VK_OEM_COMMA
#define KEY_PERIOD VK_OEM_PERIOD
#define KEY_SLASH VK_OEM_2
#define KEY_CAPS_LOCK VK_CAPITAL
#define KEY_F1 VK_F1
#define KEY_F2 VK_F2
#define KEY_F3 VK_F3
#define KEY_F4 VK_F4
#define KEY_F5 VK_F5
#define KEY_F6 VK_F6
#define KEY_F7 VK_F7
#define KEY_F8 VK_F8
#define KEY_F9 VK_F9
#define KEY_F10 VK_F10
#define KEY_F11 VK_F11
#define KEY_F12 VK_F12
#define KEY_PRINT_SCREEN VK_SNAPSHOT
#define KEY_SCROLL_LOCK VK_SCROLL
#define KEY_PAUSE VK_PAUSE
#define KEY_INSERT VK_INSERT
#define KEY_HOME VK_HOME
#define KEY_PAGE_UP VK_PRIOR
#define KEY_DELETE VK_DELETE
#define KEY_END VK_END
#define KEY_PAGE_DOWN VK_NEXT
#define KEY_RIGHT VK_RIGHT
#define KEY_LEFT VK_LEFT
#define KEY_DOWN VK_DOWN
#define KEY_UP VK_UP
#define KEY_NUMLOCK VK_NUMLOCK
#define KEY_KP0 VK_NUMPAD0
#define KEY_KP1 VK_NUMPAD1
#define KEY_KP2 VK_NUMPAD2
#define KEY_KP3 VK_NUMPAD3
#define KEY_KP4 VK_NUMPAD4
#define KEY_KP5 VK_NUMPAD5
#define KEY_KP6 VK_NUMPAD6
#define KEY_KP7 VK_NUMPAD7
#define KEY_KP8 VK_NUMPAD8
#define KEY_KP9 VK_NUMPAD9
#define KEY_KPASTERISK VK_MULTIPLY
#define KEY_KPPLUS VK_ADD
#define KEY_KPMINUS VK_SUBTRACT
#define KEY_KPDOT VK_DECIMAL
#define KEY_KPSLASH VK_DIVIDE
#define KEY_F13 VK_F13
#define KEY_F14 VK_F14
#define KEY_F15 VK_F15
#define KEY_F16 VK_F16
#define KEY_F17 VK_F17
#define KEY_F18 VK_F18
#define KEY_F19 VK_F19
#define KEY_F20 VK_F20
#define KEY_F21 VK_F21
#define KEY_F22 VK_F22
#define KEY_F23 VK_F23
#define KEY_F24 VK_F24
#define KEY_TILE VK_OEM_3
#define KEY_SHIFT VK_SHIFT
#define KEY_CONTROL VK_CONTROL
#define KEY_ALT VK_MENU
#define KEY_LEFT_ALT VK_LMENU
#define KEY_LEFT_CONTROL VK_LCONTROL
#define KEY_LEFT_SHIFT VK_LSHIFT
#define KEY_RIGHT_ALT VK_RMENU
#define KEY_RIGHT_CONTROL VK_RCONTROL
#define KEY_RIGHT_SHIFT VK_RSHIFT
#define KEY_LEFT_WINDOWS VK_LWIN
#define KEY_RIGHT_WINDOWS VK_RWIN
#elif defined(__linux__)
#include <linux/input-event-codes.h> // has definitions for KEY_* macros
#define KEY_LEFT_ARROW KEY_LEFT
#define KEY_RIGHT_ARROW KEY_RIGHT
#define KEY_UP_ARROW KEY_UP
#define KEY_DOWN_ARROW KEY_DOWN
#elif defined(__APPLE__)
#define KEY_A 0x00
#define KEY_S 0x01
#define KEY_D 0x02
#define KEY_F 0x03
#define KEY_H 0x04
#define KEY_G 0x05
#define KEY_Z 0x06
#define KEY_X 0x07
#define KEY_C 0x08
#define KEY_V 0x09
#define KEY_B 0x0B
#define KEY_Q 0x0C
#define KEY_W 0x0D
#define KEY_E 0x0E
#define KEY_R 0x0F
#define KEY_Y 0x10
#define KEY_T 0x11
#define KEY_1 0x12
#define KEY_2 0x13
#define KEY_3 0x14
#define KEY_4 0x15
#define KEY_6 0x16
#define KEY_5 0x17
#define KEY_EQUAL 0x18
#define KEY_9 0x19
#define KEY_7 0x1A
#define KEY_MINUS 0x1B
#define KEY_8 0x1C
#define KEY_0 0x1D
#define KEY_RIGHT_BRACKET 0x1E
#define KEY_O 0x1F
#define KEY_U 0x20
#define KEY_LEFT_BRACKET 0x21
#define KEY_I 0x22
#define KEY_P 0x23
#define KEY_RETURN 0x24
#define KEY_L 0x25
#define KEY_J 0x26
#define KEY_APOSTROPHE 0x27
#define KEY_K 0x28
#define KEY_SEMICOLON 0x29
#define KEY_BACKSLASH 0x2A
#define KEY_COMMA 0x2B
#define KEY_SLASH 0x2C
#define KEY_N 0x2D
#define KEY_M 0x2E
#define KEY_PERIOD 0x2F
#define KEY_TAB 0x30
#define KEY_SPACE 0x31
#define KEY_TILDE 0x32
#define KEY_DELETE 0x33
#define KEY_ESCAPE 0x35
#define KEY_RIGHT_COMMAND 0x36
#define KEY_COMMAND 0x37
#define KEY_SHIFT 0x38
#define KEY_CAPSLOCK 0x39
#define KEY_OPTION 0x3A
#define KEY_CONTROL 0x3B
#define KEY_RIGHT_SHIFT 0x3C
#define KEY_RIGHT_OPTION 0x3D
#define KEY_RIGHT_CONTROL 0x3E  
#define KEY_FUNCTION 0x3F
#define KEY_F17 0x40
#define KEY_KPASTERISK 0x43
#define KEY_VOLUMEUP 0x48
#define KEY_VOLUMEDOWN 0x49
#define KEY_MUTE 0x4A
#define KEY_F18 0x4F
#define KEY_F19 0x50
#define KEY_KPEQUAL 0x51
#define KEY_KP0 0x52
#define KEY_KP1 0x53
#define KEY_KP2 0x54
#define KEY_KP3 0x55
#define KEY_KP4 0x56
#define KEY_KP5 0x57
#define KEY_KP6 0x58
#define KEY_KP7 0x59
#define KEY_F20 0x5A
#define KEY_KP8 0x5B
#define KEY_KP9 0x5C
#define KEY_F5 0x60
#define KEY_F6 0x61
#define KEY_F7 0x62
#define KEY_F3 0x63
#define KEY_F8 0x64
#define KEY_F9 0x65
#define KEY_F11 0x67
#define KEY_F13 0x69
#define KEY_F16 0x6A
#define KEY_F14 0x6B
#define KEY_F10 0x6D
#define KEY_F12 0x6F
#define KEY_F15 0x71
#define KEY_HELP 0x72
#define KEY_HOME 0x73
#define KEY_F4 0x76
#define KEY_F2 0x78
#define KEY_F1 0x7A
#define KEY_LEFT_ARROW 0x7B
#define KEY_RIGHT_ARROW 0x7C
#define KEY_DOWN_ARROW 0x7D
#define KEY_UP_ARROW 0x7E
#endif
#ifdef __cplusplus
}
#endif