name: Feature Request
description: Request an addition or removal of cmdfx.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a cmdfx feature. Please fill out the information below.
  - type: dropdown
    attributes:
      label: Feature Type
      description: What area of improvement would you suggest?
      multiple: false
      options:
        - Optimization
        - Compatibility
        - Documentation
        - New Feature
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of Feature
      placeholder: |
        Ex: Please add support for graphics on xxx
    validations:
      required: true
