name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2022
          - macos-13
          - macos-15

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-dotnet@v4
        if: ${{ matrix.os == 'windows-2022' }}
        with:
          dotnet-version: '9'
      - name: Install WiX
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          dotnet tool install --global wix --version 5.0.2
          wix extension add --global WixToolset.UI.wixext/5.0.2
      - name: Install Kotlin
        if: ${{ matrix.os != 'ubuntu-24.04-arm' }}
        uses: fwilhe2/setup-kotlin@main
        with:
          version: '2.1.10'
          install-native: true
      - name: Setup Konan
        if: ${{ matrix.os != 'ubuntu-24.04-arm' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/caches
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-*
            /root/.konan/caches
            /root/.konan/dependencies
            /root/.konan/kotlin-native-prebuilt-*
          key: ${{ runner.os }}-${{ runner.arch }}-konan
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-konan
      - name: Link CInterop Command
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: |
          sudo ln -s $KOTLIN_NATIVE_HOME/bin/cinterop /usr/local/bin/cinterop
          sudo ln -s $KOTLIN_NATIVE_HOME/bin/run_konan /usr/local/bin/run_konan
          sudo ln -s $KOTLIN_NATIVE_HOME/bin/kotlinc-native /usr/local/bin/kotlinc-native
      - name: Configure Project
        run: cmake -B build -DPROJECT_VERSION_SUFFIX=${GITHUB_SHA::7} -DSAMPLES_CMDFX=ON
        shell: bash
      - name: Build Project (Linux/MacOS)
        if: ${{ matrix.os != 'windows-2022' }}
        run: |
          sudo cmake --build build --config Debug --target install package
          sudo rm -rf build/build/package/_CPack_Packages/
      - name: Build Project (Windows)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          cmake --build build --config Debug --target install package
          Get-ChildItem -Path build/build/package/_CPack_Packages -Recurse | Remove-Item -Recurse -Force
      - name: Archive Package Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: CmdFX-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          path: |
            build/build/package/*
            build/build/cinterop/*
          overwrite: true
          if-no-files-found: error
      - name: Test Project (Windows)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          cd build
          ctest -C Debug -T test -j0 --output-on-failure
          cd ..
      - name: Test Project (Posix)
        if: ${{ matrix.os != 'windows-2022' }}
        run: |
          cd build
          sudo ctest -C Debug -T test -j0 --output-on-failure
          cd ..
      - name: Archive Test Reports
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: CmdFX-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}-test
          path: build/Testing/*
          if-no-files-found: ignore
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy Doxygen
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
      - name: Configure Project
        run: cmake -B build
      - name: Build Docs
        run: cmake --build build --target docs
      - name: Deploy Doxygen
        run: bash doxygen.sh ${GITHUB_SHA::7}
  
  publish:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-24.04
          - windows-2022
          - macos-13
          - macos-15
    
    needs: build
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Maven Settings
        if: ${{ matrix.os != 'ubuntu-24.04-arm' }}
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: '[{"id": "calcugames", "username": "${{ secrets.MAVEN_USERNAME_CALCUGAMES }}", "password": "${{ secrets.MAVEN_PASSWORD_CALCUGAMES }}"}]'
      - name: Install Kotlin
        if: ${{ matrix.os != 'ubuntu-24.04-arm' }}
        uses: fwilhe2/setup-kotlin@main
        with:
          version: '2.1.10'
          install-native: true
      - name: Setup Konan
        if: ${{ matrix.os != 'ubuntu-24.04-arm' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/caches
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-*
            /root/.konan/caches
            /root/.konan/dependencies
            /root/.konan/kotlin-native-prebuilt-*
          key: ${{ runner.os }}-${{ runner.arch }}-konan
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-konan
      - name: Set Artifact ID
        id: set_artifact_id
        run: |
          RUNNER_OS=$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')
          RUNNER_ARCH=$(echo ${{ runner.arch }} | tr '[:upper:]' '[:lower:]')
          echo "KN_INSTALL_ARTIFACTID=cmdfx-$RUNNER_OS-$RUNNER_ARCH" >> $GITHUB_ENV
        shell: bash
      - name: Link CInterop Command
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: |
          sudo ln -s $KOTLIN_NATIVE_HOME/bin/cinterop /usr/local/bin/cinterop
          sudo ln -s $KOTLIN_NATIVE_HOME/bin/run_konan /usr/local/bin/run_konan
          sudo ln -s $KOTLIN_NATIVE_HOME/bin/kotlinc-native /usr/local/bin/kotlinc-native
      - name: Configure Project
        run: cmake -B build -DPROJECT_VERSION_SUFFIX=SNAPSHOT -DKN_INSTALL_ARTIFACTID="${{ env.KN_INSTALL_ARTIFACTID }}" -DTEST_CMDFX=OFF
        shell: bash
      - name: Publish Kotlin/Native Library
        run: cmake --build build --config Debug --target klib deploy-maven
