name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2022
          - macos-13
          - macos-15

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        if: ${{ matrix.os == 'windows-2022' }}
        with:
          dotnet-version: '9'
      - name: Configure Project
        run: cmake .
      - name: Build Project (Linux/MacOS)
        if: ${{ matrix.os != 'windows-2022' }}
        run: |
          sudo cmake --build . --config Debug --target install package
          sudo rm -rf build/package/_CPack_Packages/
      - name: Build Project (Windows)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          dotnet tool install --global wix
          wix extension add --global WixToolset.UI.wixext
          cmake --build . --config Debug --target install package
          del /s /q build/package/_CPack_Packages
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          path: build/bin/*
          overwrite: true
          if-no-files-found: ignore
      - name: Archive Package Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: CmdFX-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          path: build/package/*
          overwrite: true
      - name: Test Project
        run: ctest -C Debug -T test
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy Doxygen
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
      - name: Configure Project
        run: cmake .
      - name: Build Docs
        run: make docs
      - name: Deploy Doxygen
        run: bash doxygen.sh ${GITHUB_SHA::7}
