name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'
      - name: Configure Project
        run: cmake .
      - name: Build Project (Linux/MacOS)
        if: ${{ matrix.os != 'windows-latest' }}
        run: sudo cmake --build . --config Debug --target install package
      - name: Build Project (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          dotnet tool install --global wix
          cmake --build . --config Debug --target install package
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ runner.os }}
          path: build/bin/Debug
          overwrite: true
      - name: Archive Package Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cmdfx-${{ runner.os }}-${{ github.sha }}
          path: |
            build/package/*
            !build/package/_CPack_Packages
      - name: Test Project
        run: ctest -C Debug -T test
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy Doxygen
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
      - name: Configure Project
        run: cmake .
      - name: Build Docs
        run: make docs
      - name: Deploy Doxygen
        run: bash doxygen.sh ${GITHUB_SHA::7}