name: Release Project

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2022
          - macos-13
          - macos-15

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        if: ${{ matrix.os == 'windows-2022' }}
        with:
          dotnet-version: '9'
      - name: Configure Project
        run: cmake .
      - name: Build Project (Linux/MacOS)
        if: ${{ matrix.os != 'windows-2022' }}
        run: |
          sudo cmake --build . --config Release --target install package
          sudo rm -rf build/package/_CPack_Packages/
      - name: Build Project (Windows)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          dotnet tool install --global wix
          wix extension add --global WixToolset.UI.wixext
          cmake --build . --config Release --target install package
          rd /s /q build/package/_CPack_Packages
      - name: Archive Package Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: CmdFX-Release-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          path: build/package/*
          overwrite: true
  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Extract Version from CMakeLists.txt
        id: get_version
        run: |
          VERSION=$(grep -Po '(?<=set\(PROJECT_VERSION ")[^"]*' CMakeLists.txt)
          echo "Extracted Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Download Release Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: CmdFX-Release-*
          path: build/package
          merge-multiple: true
      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: "release.json"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/package/*
          tag_name: v${{ env.VERSION }}
          name: cmdfx v${{ env.VERSION }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false


